src/website/lunnarfall/urls.py
from django.conf.urls import url, include
from . import views

app_name='lunnarfall'

urlpatterns = [
    url(r'^$', views.index_view, name='index'),
]

src/website/pessoa/urls.py
from django.conf.urls import url
from . import views

app_name='pessoa'

urlpatterns = [
    url(r'^$', views.PessoaIndexView.as_view(), name='index'),
    url(r'^cliente/$', views.ClienteIndexView.as_view(), name='cliente_index'),
    url(r'^cliente/(?P<pk>[0-9]+)/$', views.ClienteDetailView.as_view(), name='detail'),
    url(r'^funcionario/$', views.FuncionarioIndexView.as_view(), name='funcionario_index'),
    url(r'^funcionario/(?P<pk>[0-9]+)/$', views.FuncionarioDetailView.as_view(), name='detail'),
]

src/website/quarto/urls.py
from django.conf.urls import url
from . import views

app_name='quarto'

urlpatterns = [
    url(r'^$', views.QuartoIndexView.as_view(), name='index'),
    url(r'^quarto/(?P<pk>[0-9]+)/$', views.QuartoDetailView.as_view(), name='quarto_detail')
]

src/website/website/urls.py
from django.conf.urls import url, include
from django.contrib import admin

admin.autodiscover()

urlpatterns = [
    url(r'^', include('lunnarfall.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^pessoa/', include('pessoa.urls')),
    url(r'^quarto/', include('quarto.urls')),
]

src/website/lunnarfall/models.py
from django.db import models

src/website/pessoa/models.py
from django.db import models


class Pessoa(models.Model):
    nome = models.CharField(max_length=200)
    cpf = models.CharField(max_length=11)
    endereco = models.TextField(blank=True)

    class Meta:
        abstract = True

    def __str__(self):
        return 'Nome: ' + self.nome + ' CPF:' + self.cpf + '\n'


class Cliente(Pessoa):
    data_cadastro = models.DateField()
    despesa_total = models.DecimalField(decimal_places=2, max_digits=10, default=0)

    def __str__(self):
        response = 'Nome: ' + self.nome + ' CPF: ' + self.cpf + ' Despesa: ' + str(self.despesa_total) + '\n'
        return response


class Funcionario(Pessoa):
    CARGO = (
        ('C', 'Chefe'),
        ('M', 'Master'),
        ('J', 'Jedi'),
    )
    data_admissao = models.DateField()
    salario = models.DecimalField(decimal_places=2, max_digits=10)
    cargo = models.CharField(max_length=1, choices=CARGO)

src/website/quarto/models.py
from django.db import models
from pessoa.models import Cliente

class Categoria(models.Model):
    NIVEL = (
        (1, 'Top'),
        (2, 'Topper'),
    )
    nome_categoria = models.IntegerField(choices=NIVEL)
    # TODO:
    # valor quarto podia ser gerado conforme o nivel
    valor_quarto = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        response = 'Top' if self.nome_categoria == 1 else 'Topper'
        response += ', '
        response += str(self.valor_quarto)
        return response

class Quarto(models.Model):
    ESTADO = (
        ('Disponível', 'Disponível'),
        ('Ocupado', 'Ocupado'),
        ('Em faxina', 'Em faxina'),
    )
    numero = models.IntegerField()
    descricao_quarto = models.TextField()
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    estado = models.CharField(max_length=20, choices=ESTADO)

    def __str__(self):
        response = str(self.numero) + ', ' + str(self.descricao_quarto) \
                   + ', ' + str(self.categoria) + ', ' + str(self.estado)
        return response

class Reserva(models.Model):
    cliente = models.ForeignKey(Cliente, blank=True, null=True, on_delete=models.SET_NULL)
    quarto = models.ForeignKey(Quarto, blank=True, null=True, on_delete=models.SET_NULL)
    data_reserva = models.DateField()
    num_diarias = models.IntegerField()
    # TODO: mais um atributo que pode ser gerado
    valor_reserva = models.DecimalField(decimal_places=2, max_digits=10)

    def __str__(self):
        response = str(self.cliente)
        return response

src/website/lunnarfall/views.py
from django.shortcuts import render
from django.views import generic
from pessoa.models import Cliente, Funcionario
from quarto.models import Quarto

class IndexView(generic.TemplateView):
    template_name = 'index.html'

def index_view(request):
    many_clientes = Cliente.objects.count()
    many_funcionarios = Funcionario.objects.count()
    many_rooms_available = Quarto.objects.filter(estado='Disponível').count()
    context = {
        'data': {
            'name_header': 'Início',
            'many_clientes': many_clientes,
            'many_funcionarios': many_funcionarios,
            'many_rooms_available': many_rooms_available,
        },
    }
    return render(request, 'index.html', context)

src/website/pessoa/views.py
# Para saber como funciona Generic Views
# https://www.youtube.com/watch?v=c3yB0_4Yd48&index=29&list=PL6gx4Cwl9DGBlmzzFcLgDhKTTfNLfX1IK
from django.views import generic

# from django.shortcuts import render
from .models import Cliente, Funcionario

# For join two QuerySets
from itertools import chain

class PessoaIndexView(generic.ListView):
    template_name = 'pessoa/index.html'
    context_object_name = 'data'

    def get_queryset(self):
        all = list(chain(Cliente.objects.all(), Funcionario.objects.all()))
        response = {
            'name_header': 'Pessoa',
            'all_people': all,
        }
        return response

class ClienteIndexView(PessoaIndexView):
    template_name = 'pessoa/cliente_list.html'

    def get_queryset(self):
        all = Cliente.objects.all()
        response = {
            'name_header': 'Cliente',
            'all_people': all,
        }
        return response

class ClienteDetailView(generic.DetailView):
    model = Cliente
    template_name = 'detail.html'

class FuncionarioIndexView(PessoaIndexView):
    template_name = 'pessoa/funcionario_list.html'

    def get_queryset(self):
        all = Funcionario.objects.all()
        response = {
            'name_header': 'Funcionario',
            'all_people': all,
        }
        return response

class FuncionarioDetailView(generic.DetailView):
    model = Funcionario
    template_name = 'detail.html'

src/website/quarto/views.py
from django.shortcuts import render
from django.views import generic

from .models import Quarto, Reserva

class QuartoIndexView(generic.ListView):
    template_name = 'quarto/index.html'
    context_object_name = 'data'

    def get_queryset(self):
        all = Quarto.objects.all()
        response = {
            'name_header': 'Quarto(s)',
            'quartos': all,
        }
        return response

class QuartoDetailView(generic.DetailView):
    model = Quarto
    template_name = 'quarto/quarto_detail.html'
    context_object_name = 'data'

    def get_context_data(self, **kwargs):
        context = super(QuartoDetailView, self).get_context_data(**kwargs)
        return context

class ReservaIndexView(generic.ListView):
    template_name = 'quarto/reserva_list.html'
    context_object_name = 'data'

    def get_queryset(self):
        all = Reserva.objects.all()
        response = {
            'name_header': 'Reserva(s)',
            'reservas': all,
        }
        return response

src/website/lunnarfall/templates/base/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Lunnarfall INN{% endblock %}</title>
    {% load staticfiles %}
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <!-- exemplo style -->
    <link rel="stylesheet" href="{% static 'exemplo/css/AdminLTE.min.css' %}">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="{% static 'exemplo/css/skins/_all-skins.min.css' %}">
    <!-- iCheck -->
    <link rel="stylesheet" href="{% static 'plugins/iCheck/flat/blue.css' %}">
    <!-- Morris chart -->
    <link rel="stylesheet" href="{% static 'plugins/morris/morris.css' %}">
    <!-- jvectormap -->
    <link rel="stylesheet" href="{% static 'plugins/jvectormap/jquery-jvectormap-1.2.2.css' %}">
    <!-- Date Picker -->
    <link rel="stylesheet" href="{% static 'plugins/datepicker/datepicker3.css' %}">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="{% static 'plugins/daterangepicker/daterangepicker.css' %}">
    <!-- bootstrap wysihtml5 - text editor -->
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css' %}">
</head>
<body class="skin-blue sidebar-mini wysihtml5-supported" style="height: auto;">
<div class="wrapper" style="height: auto;">

    <header class="main-header">
        <!-- Logo -->
        <a href="{% url 'lunnarfall:index' %}" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><b>L</b>FINN</span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg"><b>LunnarFall</b>INN</span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>

            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="{% static 'exemplo/img/user2-160x160.jpg' %}" class="user-image" alt="User Image">
                            <span class="hidden-xs">Capitão Nascimento</span>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- User image -->
                            <li class="user-header">
                                <img src="{% static 'exemplo/img/user2-160x160.jpg' %}" class="img-circle"
                                     alt="User Image">

                                <p>
                                    Capitao Nascimento - Web Developer
                                    <small>Membro desde Julho. 2017</small>
                                </p>
                            </li>
                            <!-- Menu Body -->
                            <li class="user-body">
                                <div class="row">
                                    <div class="col-xs-4 text-center">
                                        <a href="#">Followers</a>
                                    </div>
                                    <div class="col-xs-4 text-center">
                                        <a href="#">Sales</a>
                                    </div>
                                    <div class="col-xs-4 text-center">
                                        <a href="#">Friends</a>
                                    </div>
                                </div>
                                <!-- /.row -->
                            </li>
                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <div class="pull-left">
                                    <a href="#" class="btn btn-default btn-flat">Profile</a>
                                </div>
                                <div class="pull-right">
                                    <a href="#" class="btn btn-default btn-flat">Sign out</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar" style="height: auto;">
            <!-- Sidebar user panel -->
            <div class="user-panel">
                <div class="pull-left image">
                    <img src="{% static 'exemplo/img/user2-160x160.jpg' %}" class="img-circle" alt="User Image">
                </div>
                <div class="pull-left info">
                    <p>Capitão Nascimento</p>
                    <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                </div>
            </div>
            <!-- sidebar menu: : style can be found in sidebar.less -->
            <ul class="sidebar-menu">
                <li class="header">MAIN NAVIGATION</li>
                <li>
                    <a href="{% url 'pessoa:index' %}">
                        <i class="fa fa-user"></i>
                        <span>Pessoas</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'pessoa:cliente_index' %}">
                        <i class="fa fa-user"></i>
                        <span>Pessoas</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'pessoa:funcionario_index' %}">
                        <i class="fa fa-user"></i>
                        <span>Pessoas</span>
                    </a>
                </li>
            </ul>
        </section>
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper" style="min-height: 1114px;">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                {{ data.name_header }}
            </h1>
        </section>

        {% block body %}
        {% endblock %}
    </div>
    <!-- /.content-wrapper -->
{#    <footer class="main-footer">#}
{#        <div class="pull-right hidden-xs">#}
{#            <b>Version</b> 2.3.12#}
{#        </div>#}
{#        <strong>Copyright © 2014-2016 <a href="http://almsaeedstudio.com">Almsaeed Studio</a>.</strong> All rights#}
{#        reserved.#}
{#    </footer>#}

</div>
<!-- ./wrapper -->

<!-- jQuery 2.2.3 -->
<script src="{% static 'plugins/jQuery/jquery-2.2.3.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<!-- Morris.js charts -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
<script src="{% static 'plugins/morris/morris.min.js' %}"></script>
<!-- Sparkline -->
<script src="{% static 'plugins/sparkline/jquery.sparkline.min.js' %}"></script>
<!-- jvectormap -->
<script src="{% static 'plugins/jvectormap/jquery-jvectormap-1.2.2.min.js' %}"></script>
<script src="{% static 'plugins/jvectormap/jquery-jvectormap-world-mill-en.js' %}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static 'plugins/knob/jquery.knob.js' %}"></script>
<!-- daterangepicker -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.2/moment.min.js"></script>
<script src="{% static 'plugins/daterangepicker/daterangepicker.js' %}"></script>
<!-- datepicker -->
<script src="{% static 'plugins/datepicker/bootstrap-datepicker.js' %}"></script>
<!-- Bootstrap WYSIHTML5 -->
<script src="{% static 'plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js' %}"></script>
<!-- Slimscroll -->
<script src="{% static 'plugins/slimScroll/jquery.slimscroll.min.js' %}"></script>
<!-- FastClick -->
<script src="{% static 'plugins/fastclick/fastclick.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'exemplo/js/app.min.js' %}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static 'exemplo/js/pages/dashboard.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'exemplo/js/demo.js' %}"></script>

</body>
</html>

src/website/lunnarfall/templates/detail.html
{% extends 'base/base.html' %}
{#{% block albums_active %}active{% endblock %}#}

{% block body %}

OPA

{% endblock %}

src/website/lunnarfall/templates/index.html
{% extends 'base/base.html' %}
{#{% block albums_active %}active{% endblock %}#}

{% block body %}<!-- Content Header (Page header) -->

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <a href="{% url 'pessoa:cliente_index' %}">
                <div class="col-md-3 col-sm-6 col-xs-12">
                    <div class="info-box">
                        <span class="info-box-icon bg-aqua"><i class="ion ion-ios-people-outline"></i></span>

                        <div class="info-box-content">
                            <span class="info-box-text">Clientes</span>
                            <span class="info-box-number">{{ data.many_clientes }}</span>
                        </div>
                        <!-- /.info-box-content -->
                    </div>
                    <!-- /.info-box -->
                </div>
            </a>
            <!-- /.col -->
            <a href="{% url 'pessoa:funcionario_index' %}">
                <div class="col-md-3 col-sm-6 col-xs-12">
                    <div class="info-box">
                        <span class="info-box-icon bg-yellow"><i class="ion ion-ios-people"></i></span>

                        <div class="info-box-content">
                            <span class="info-box-text">Funcionarios</span>
                            <span class="info-box-number">{{ data.many_funcionarios }}</span>
                        </div>
                        <!-- /.info-box-content -->
                    </div>
                    <!-- /.info-box -->
                </div>
            </a>

            <!-- fix for small devices only -->
            {#        <div class="clearfix visible-sm-block"></div>#}
            {#        <!-- /.col -->#}
            {#        <div class="col-md-3 col-sm-6 col-xs-12">#}
            {#            <div class="info-box">#}
            {#                <span class="info-box-icon bg-red"><i class="fa fa-google-plus"></i></span>#}
            {##}
            {#                <div class="info-box-content">#}
            {#                    <span class="info-box-text">Likes</span>#}
            {#                    <span class="info-box-number">41,410</span>#}
            {#                </div>#}
            {#                <!-- /.info-box-content -->#}
            {#            </div>#}
            {#            <!-- /.info-box -->#}
            {#        </div>#}
            {#        <!-- /.col -->#}

            <a href="{% url 'quarto:index' %}">
            <div class="col-md-3 col-sm-6 col-xs-12">
                <div class="info-box">
                    <span class="info-box-icon bg-green"><i class="ion ion-ios-checkmark"></i></span>

                    <div class="info-box-content">
                        <span class="info-box-text">Quartos disponiveis</span>
                        <span class="info-box-number">{{ data.many_rooms_available }}</span>
                    </div>
                    <!-- /.info-box-content -->
                </div>
                <!-- /.info-box -->
            </div>
            </a>
            <!-- /.col -->

        </div>
    </section>
{% endblock %}

src/website/lunnarfall/templates/pessoa/cliente_list.html
{% extends 'base/base.html' %}
{#{% block albums_active %}active{% endblock %}#}

{% block body %}
    <ul>
    <div class="box">
        <div class="box-header">
          <h3 class="box-title">Clientes</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
          <table id="example1" class="table table-bordered table-striped">
            <thead>
            <tr>
                <th>Nome</th>
                <th>CPF</th>
                <th>Endereço</th>
                <th>Data cadastro</th>
                <th>Despesa Total</th>
            </tr>
            </thead>
            <tbody>
            {% for cliente in all_people %}
                <tr>
                    <td><a href="{% url 'pessoa:detail' cliente.pk %}">{{ cliente.nome }}</a></td>
                    <td>{{ cliente.cpf }}</td>
                    <td>{{ cliente.endereco }}</td>
                    <td>{{ cliente.data_cadastro }}</td>
                    <td>{{ cliente.despesa_total }}</td>
                    {#              <td><i class="fa fa-check"></i></td>#}
                </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
        <!-- /.box-body -->
      </div>

    </ul>


{% endblock %}

src/website/lunnarfall/templates/pessoa/funcionario_list.html
{% extends 'base/base.html' %}
{#{% block albums_active %}active{% endblock %}#}

{% block body %}
    <!-- Main content -->
    <section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Lista de funcionarios</h3>

                    <div class="box-tools">
                        <div class="input-group input-group-sm" style="width: 150px;">
                            <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">

                            <div class="input-group-btn">
                                <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body table-responsive no-padding">
                    <table class="table table-hover">
                        <tbody>
                        <tr>
                            <th>Nome</th>
                            <th>CPF</th>
                            <th>Endereço</th>
                            <th>Data cadastro</th>
                            <th>Despesa Total</th>
                            <th>Cargo</th>
                        </tr>
                        {% for funcionario in data.all_people %}
                            <tr>
                                <td><a href="{% url 'pessoa:detail' funcionario.pk %}">{{ funcionario.nome }}</a></td>
                                <td>{{ funcionario.cpf }}</td>
                                <td>{{ funcionario.endereco }}</td>
                                <td>{{ funcionario.data_admissao }}</td>
                                <td>{{ funcionario.salario }}</td>
                                <td>{{ funcionario.cargo }}</td>
                            </tr>
                        {% endfor %}

                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
    </div>
    </section>
{% endblock %}

src/website/lunnarfall/templates/pessoa/index.html
{% extends 'base/base.html' %}
{#{% block albums_active %}active{% endblock %}#}

{% block body %}
    <ul>
    <div class="box">
        <div class="box-header">
          <h3 class="box-title">Usuarios</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
          <table id="example1" class="table table-bordered table-striped">
            <thead>
            <tr>
              <th>Nome</th>
              <th>CPF</th>
              <th>Endereço</th>
            </tr>
            </thead>
            <tbody>
            {% for cliente in data.all_people %}
                <tr>
                  <td><a href="{% url 'pessoa:detail' cliente.pk %}">{{ cliente.nome }}</a></td>
                  <td>{{ cliente.cpf }}</td>
                  <td>{{ cliente.endereco }}</td>
                </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
        <!-- /.box-body -->
      </div>

    </ul>


{% endblock %}

src/website/lunnarfall/templates/quarto/index.html
{% extends 'base/base.html' %}

{% block body %}
    <!-- Main content -->
    <section class="content">
        <div class="row">
            {% for quarto in data.quartos %}

                <div class="col-md-3 col-sm-6 col-xs-12">
                    <a href="{% url 'quarto:quarto_detail' quarto.pk %}">
                    {% if quarto.estado == 'Disponível' %}
                    <div class="info-box bg-green">
                        <span class="info-box-icon"><i class="glyphicon glyphicon-plus"></i></span>
                    {% elif quarto.estado == 'Ocupado' %}
                    <div class="info-box bg-red">
                        <span class="info-box-icon"><i class="glyphicon glyphicon-user"></i></span>
                    {% elif quarto.estado == 'Em faxina' %}
                    <div class="info-box bg-yellow">
                        <span class="info-box-icon"><i class="glyphicon glyphicon-alert"></i></span>
                    {% endif %}
                        <div class="info-box-content">
                            <span class="info-box-text">Quarto {{ quarto.numero }}</span>
                            <span class="info-box-number">{{ quarto.estado }}</span>
                        </div>
                <!-- /.info-box-content -->
                    </div></a>
                <!-- /.info-box -->
                </div>
            {% endfor %}

        </div>
    </section>

{% endblock %}

src/website/lunnarfall/templates/quarto/quarto_detail.html
{% extends 'base/base.html' %}

{% block body %}
    <h1>{{ data.numero }}</h1>
    <p>{{ data.descricao_quarto }}</p>
    <p>{{ data.categoria }}</p>
    <p>{{ data.estado }}</p>
{% endblock %}

src/website/lunnarfall/templates/quarto/reserva_list.html
{% extends 'base/base.html' %}

{% block body %}
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Lista de Quartos</h3>

                        <div class="box-tools">
                            <div class="input-group input-group-sm" style="width: 150px;">
                                <input type="text" name="table_search" class="form-control pull-right"
                                       placeholder="Search">

                                <div class="input-group-btn">
                                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body table-responsive no-padding">
                        <table class="table table-hover">
                            <tbody>
                            <tr>
                                <th>Numero</th>
                                <th>Descricao</th>
                                <th>Categoria</th>
                            </tr>
                            {% for reserva in data.reservas %}
                                <tr>
{#                                    TODO: obviamente mexer aqui#}
                                </tr>
                            {% endfor %}

                            </tbody>
                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
        </div>
    </section>

{% endblock %}